version: "3"
services:
  app:
    container_name: ${CONTAINER_NAME}-app
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    expose:
      - 9005
      - 9000
    volumes:
      - ./:/app
    env_file: .env
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - './docker/nginx/nginx.template:/etc/nginx/conf.d/nginx.template'
      - './:/app'
      - './development/logs/nginx:/var/log/nginx'
    ports:
      - ${DOMAIN_PORT}:${DOMAIN_PORT}
    env_file: .env
    command: sh -c "envsubst '$$NGINX_CDN_HOST $$NGINX_CDN_PORT $$NGINX_CDN_DIR $$NGINX_API_HOST $$NGINX_API_PORT $$NGINX_API_DIR $$NGINX_BACKEND_HOST $$NGINX_BACKEND_PORT $$NGINX_BACKEND_DIR $$NGINX_FRONTEND_HOST $$NGINX_FRONTEND_PORT $$NGINX_FRONTEND_DIR $$DOMAIN_PORT $$CONTAINER_NAME' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
        - app
  mysql:
    container_name: ${CONTAINER_NAME}-mysql
    build: ./docker/mysql
    env_file: .env
    volumes:
      - ./development/server/mysql:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - ${MYSQL_PORT}:3306
  postgres:
    container_name: ${CONTAINER_NAME}-postgres
    build: ./docker/postgres
    restart: always
    env_file: .env
    volumes:
      - './development/server/postgres:/var/lib/postgresql'
    ports:
      - ${POSTGRES_PORT}:5432
  memcache:
    container_name: ${CONTAINER_NAME}-memcache
    env_file: .env
    image: 'memcached:alpine'
    restart: always
  rabbitmq:
    container_name: ${CONTAINER_NAME}-rabbitmq
    image: 'rabbitmq:alpine'
    restart: always
    env_file: .env
    ports:
      - '8080:15672'
      - '5672:5672'
      - '4369:4369'
      - '25672:25672'
    volumes:
      - './development/server/rabbitmq:/var/lib/rabbitmq'
  node:
    container_name: ${CONTAINER_NAME}-node
    env_file: .env
    image: node:9-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/true
  redis:
    container_name: ${CONTAINER_NAME}-redis
    env_file: .env
    image: redis
    ports:
      - ${REDIS_PORT}:6379
  mailcatcher:
    container_name: ${CONTAINER_NAME}-mailcatcher
    image: schickling/mailcatcher:latest
    ports:
      - ${MAILCATCHER_PORT}:1080
  swagger-ui:
    container_name: ${CONTAINER_NAME}-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_UI_PORT}:8080
    env_file: .env